select * from Bibtex.dbo.Article
select * from Bibtex.dbo.Book
select * from Bibtex.dbo.BookLet
select * from Bibtex.dbo.Conference
select * from Bibtex.dbo.InBook
select * from Bibtex.dbo.InCollection
select * from Bibtex.dbo.InProceedings
select * from Bibtex.dbo.[Manual]
select * from Bibtex.dbo.MastersThesis
select * from Bibtex.dbo.Misc
select * from Bibtex.dbo.PhdThesis
select * from Bibtex.dbo.Proceedings
select * from Bibtex.dbo.TechReport
select * from Bibtex.dbo.Unpublished