delete from Bibtex.dbo.Article
delete from Bibtex.dbo.Book
delete from Bibtex.dbo.BookLet
delete from Bibtex.dbo.Conference
delete from Bibtex.dbo.InBook
delete from Bibtex.dbo.InCollection
delete from Bibtex.dbo.InProceedings
delete from Bibtex.dbo.[Manual]
delete from Bibtex.dbo.MastersThesis
delete from Bibtex.dbo.Misc
delete from Bibtex.dbo.PhdThesis
delete from Bibtex.dbo.Proceedings
delete from Bibtex.dbo.TechReport
delete from Bibtex.dbo.Unpublished